version: '3'
services:
  server:
    build:
      context: "./src/server"
      dockerfile: "gRpcFileService-Sample.Server/Dockerfile"
    ports:
      - "7979:80"
      - "443:443"
    restart: always