version: '3'
services:
  frontend:
    build:
      context: "./src/clients"
      dockerfile: "Dockerfile"
    ports:
      - "80:80"
    restart: always
  backend:
    build:
      context: "./src/server"
      dockerfile: "gRpcFileService-Sample.Server/Dockerfile"
    ports:
      - "7979:80"
      - "443:443"
    restart: always